### PR TITLE
Updated dependencies for Node 12

### LINKED ISSUE #69: npm install fails on Node 12.10
Error: 
```
binding.cc:222:43: error: no matching function for call to ‘v8::Value::BooleanValue()’
  222 |   bool persistent = info[3]->BooleanValue();
```

### PR DESCRIPTION
**Pull request by jamesgrams**
I was having the same problem installing with Node 12 as mentioned here: https://github.com/jehervy/node-virtual-gamepads/issues/69. I was able to fix the problem by updating the dependencies on `ref`, `ref-array`, and `ref-struct` to `ref-napi`, `ref-array-napi`, and `ref-struct-napi`. Now installs and works on Ubuntu 18,04, Node version 12.13.0.

Would you please consider this pull request?

closes #69

### CODE REVIEW

**Comment by robsdedude** [comment]
I cannot get damn github to register this PR as merged after I have rebased it. It is merged into develop branch now, however. Thank you for your work! For future reference: if a project has a develop branch, this is usually where to base your PR on as it might be ahead of the master and don't forget to put your changes into the changelog and adjust docs generally.
